stages:
  - build
  - test
  - release

variables:
  VERSION: '1.0.${CI_PIPELINE_ID}'

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true
      --cache-repo "${CI_REGISTRY_IMAGE}/cache"
  artifacts:
    name: "build-frontend-$VERSION"
    paths:
      - frontend/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/.cache/
    policy: push

sast-test-frontend:
  stage: test
  trigger:
    include:
      - template: Security/SAST.gitlab-ci.yml
  needs:
    - build-frontend

docker-registry-frontend:
  stage: release
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE/momo-store-frontend:$CI_COMMIT_SHA latest
  needs:
    - sast-test-frontend
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main"'

