services:
  backend:
    container_name: backend
    image: ${CI_REGISTRY_IMAGE}/momo-backend:latest
    restart: always
    networks:
      - momo-store
    expose:
      - "8081"
  frontend:
    container_name: frontend
    image: ${CI_REGISTRY_IMAGE}/momo-frontend:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - momo-store
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
networks:
  momo-store: