stages:
  - build
  - test
  - release

variables:
  VERSION: '1.0.${CI_PIPELINE_ID}'

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true
      --cache-repo "${CI_REGISTRY_IMAGE}/cache"
  artifacts:
    name: "build-backend-$VERSION"
    paths:
      - backend/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - backend/.cache/
    policy: push

unit-test-backend:
  stage: test
  image: golang:1.17-alpine
  before_script:
    - apk add --no-cache gcc musl-dev
  script:
    - cd backend
    - go test -v ./...
  needs:
    - build-backend

sast-test-backend:
  stage: test
  trigger:
    include:
      - template: Security/SAST.gitlab-ci.yml
  needs:
    - unit-test-backend

docker-registry-backend:
  stage: release
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA latest
  needs:
    - sast-test-backend
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main"'
